### ISSUE TITLE
Transfer lengthy README info to wiki

### ISSUE THREAD

**Issue by KEYS248** [Siegallab/Flexostat-interface#2]
So apparently READMEs are supposed to be short and wiki's are for longer pieces of information including "how to use it, how it's been designed, manifestos on its core principles, and so on" (github).  
- [ ] thus shortening the README and making a wiki with the information is something that should be done
- [x] also putting the lengthy README info into a separate markdown file called WIKI so people have the info when they download the files is a good idea

**Comment by cr4zyafrican** [comment]
Hi David! I will work on the second part of this issue.

**Comment by KEYS248** [comment]
Closing this issue because I decided simply having a WIKI.MD file with a nice table of contents is similarly as good as making a whole wiki in the wiki tab of this repository
